### ISSUE TITLE
missing deployed version url on repo

### ISSUE THREAD

**Issue by vitordino** [Iemankm/web-tooling-007#1]
your repo url is pointing to your vercel dashboard ([vercel.com/iemankm/web-tooling-007](https://vercel.com/iemankm/web-tooling-007)) — and it’s only visible to you.

you just need to put the deployed application url there to get the assignment marked as complete.

other than that, everything is correct ✅

**Comment by Iemankm** [comment]
is it correct now?

**Comment by vitordino** [comment]
probably the correct one is https://web-tooling-007-iemankm.vercel.app/ (the current one points to just one commit and will not update on pushes)

**Comment by Iemankm** [comment]
okay I updated it

**Comment by vitordino** [comment]
now it’s right
feel free to close this issue
